### ISSUE TITLE
Any Algorithms in C++ are welcomed!

### ISSUE THREAD

**Issue by therohit777** [therohit777/Begginer__Friendly_Problems#2]
Any Algorithms in C++ are welcomed!

Make the contributions inside the C++ Directory in the format given below before making
PR request..
Format:
            2NDOct_Githubname.c++

**Comment by using-namespace-ruhul** [comment]
I want to add some cpp algos. Assign me for this please.  :)

**Comment by Priyanshu-792** [comment]
assign me this issue
