### ISSUE TITLE
Any Algorithms in C are welcomed!

### ISSUE THREAD

**Issue by therohit777** [therohit777/Begginer__Friendly_Problems#3]
Any Algorithms in C are welcomed!

Make the contributions inside the C Directory in the format given below before making
PR request..
Format:
2NDOct_Githubname.c

**Comment by gaurangisinha** [comment]
Hi, @therohit777. Is this a part of Hacktoberfest 2021?

**Comment by therohit777** [comment]
@gaurangisinha Yes , you can make contributions here. No need to wait for assignes just go ahead and make PRs.

**Comment by gaurangisinha** [comment]
Thanks a lot! Could you please tell me what is meant by Githubname here in the format you have provided?

**Comment by therohit777** [comment]
@gaurangisinha Your GitHub username.

**Comment by Meghwantsingh** [comment]
Hi'
I'm Meghwant singh . I'm new to this hacktoberfest but I would like to work on this project .
I knew C/C++ .

**Comment by HastiSutaria** [comment]
Hi @therohit777  Hasti Sutaria here! Would like to contribute here. I have a curated list of algorithms in c!

**Comment by HastiSutaria** [comment]
Just need to ask that should we upload source code file only or along with that we need to attach outputs?

**Comment by therohit777** [comment]
@HastiSutaria Only the Source Code file is needed.

**Comment by HastiSutaria** [comment]
@therohit777 May you please add hacktoberfest accepted label as my pr is merged.

**Comment by therohit777** [comment]
@HastiSutaria I have added the label
